[tool.ruff]
extend-exclude = ['migrations']
line-length = 88
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["I", "F", "E", "W", "N", "S", "B", "A", "FBT", "C4", "DTZ", "ASYNC", "PGH004", 
    "EM", "TCH", "SLF", "RET", "SIM", "PIE", "DJ", "TRY", "FURB", "PERF", "RUF", "PLC"]
ignore = ["PLC0414", "PLC0415", "S311", "S101", "B008"]

[tool.pytest.ini_options]
addopts = "-v"
pythonpath = "facilibras"

[tool.pyright]
exclude = ["venv"]
venvPath = "."
venv = "venv"
typeCheckingMode = "basic"
